python doctr/references/detection/train_pytorch.py db_resnet50 ^
    --device 0 ^
    --train_path data/ascii-captcha-image-doctr/detect/train ^
    --val_path data/ascii-captcha-image-doctr/detect/val ^
    --output_dir models/ascii-captcha ^
    --epochs 20 ^
    -b 4 ^
    --lr 0.001 ^
    --wd 1e-4 ^
    --input_size 640 ^
    -j 0 ^
    --sched cosine ^
    --early-stop ^
    --early-stop-epochs 5 ^
    --early-stop-delta 0.005 ^
    --pretrained ^
    --rotation ^
